#######################################################
# Makefile for CS530 Assignment 1
# Emily Jean Versoza cssc0422 RedID: 819442111
# Christina Tran cssc0466 RedID: 819312540
#######################################################

CC = gcc

xbd:	xbd.o
	$(CC) xbd.o -o xbd

xbd.o:	xbd.c xbd.h
	$(CC) -c xbd.c

clean:
	rm *.o xbd

#################[ EOF: Makefile ]#######################
